---
title: "first_try_drc"
author: "Lucie Lu"
date: "2022-11-13"
output: pdf_document
---

````{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}

library(tidyverse)
library(dplyr)
```

```{r}

data <- read_csv("https://raw.githubusercontent.com/LucieLuS/Civilwar_onset_contageous/main/conference_congo/DRC_coding_complete_all.csv?token=GHSAT0AAAAAAB3ESJMSYAVZQZPLHYE2EHKUY3RLLTA")

```


```{r}

#keep the complete cases
data2 <- data[complete.cases(data$id), ]

# 70 unique original events
unique(data2$id)
```


```{r}

#same actor
contagious <- data2 %>% group_by(id) %>% summarise_at(vars(by_actor), list(sum_same_actor_conf = sum))

#stricter definition, 
#same city, same actor for subsequent events
contagious_2 <- data2 %>% group_by(id) %>% summarise(sum_same_geo_conf = sum(by_actor[by_geography == 1]))


report <- data2 %>% group_by(id) %>% summarise_at(vars(report_binary), list(report = unique))

#merge
analy <- merge(report, contagious, by = "id")
analy <- merge(analy, contagious_2, by = "id")

#create binary variables
analy$if_same_actor_conf <- ifelse(analy$sum_same_actor_conf==0, 0, 1)
analy$if_same_geo_conf <- ifelse(analy$sum_same_geo_conf==0, 0, 1)
```

```{r}

table(analy$report)
# about half-half

table(analy$if_same_actor_conf)
# contagious events too many...

table(analy$if_same_geo_conf)
# contagious events are way more even in a stricter definition...

```

```{r}
# N = 70

lm1 <- lm(sum_same_actor_conf ~ report, data = analy)
summary(lm1)

# all positive signs, but probably not enough power

# binaryDV
lm2 <- lm(if_same_actor_conf ~ report, data = analy)
summary(lm2)

###################

# stricter definition of contagious events
lm3 <- lm(sum_same_geo_conf ~ report, data = analy)
summary(lm3)

# binaryDV2
lm4 <- lm(if_same_geo_conf ~ report, data = analy)
summary(lm4)
```


```{r}

# quantile approach
analy$quartile_same_actor_conf <- ntile(analy$sum_same_actor_conf, 4)  

lm2_2 <- lm(quartile_same_actor_conf ~ report, data = analy)
summary(lm2_2)

#########
analy$quartile_same_geo_conf <- ntile(analy$sum_same_geo_conf, 4)  

lm4_2 <- lm(quartile_same_geo_conf ~ report, data = analy)
summary(lm4_2)

```